"""Update project status states and add error_message

Revision ID: 208ec29c043f
Revises: d484f4320746
Create Date: 2025-11-08 13:12:32.494080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '208ec29c043f'
down_revision: Union[str, None] = 'd484f4320746'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add error_message column
    op.add_column('projects', sa.Column('error_message', sa.Text(), nullable=True))

    # Update existing status values
    # Convert 'active' projects to 'ready' if they have videos, otherwise 'planning'
    op.execute("""
        UPDATE projects
        SET status = CASE
            WHEN status = 'active' AND EXISTS (SELECT 1 FROM videos WHERE videos.project_id = projects.id) THEN 'ready'
            WHEN status = 'active' THEN 'planning'
            WHEN status = 'archived' THEN 'archived'
            ELSE status
        END
    """)

    # Change default for new records to 'planning'
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               server_default=sa.text("'planning'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert status values back to old system
    op.execute("""
        UPDATE projects
        SET status = CASE
            WHEN status IN ('planning', 'ready', 'processing', 'completed', 'error') THEN 'active'
            WHEN status = 'archived' THEN 'archived'
            ELSE 'active'
        END
    """)

    # Restore old default
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               server_default=sa.text("'active'::character varying"))

    # Remove error_message column
    op.drop_column('projects', 'error_message')
    # ### end Alembic commands ###
