"""Add SQLAlchemy enum enforcement on status columns (no-op DDL).

Revision ID: e4f5a6b7c8d9
Revises: c3d4e5f6g7h8
Create Date: 2026-04-07

PR #22 (state-machine-enums) switched four status columns in
``app/models/database_models.py`` from ``Column(String(50))`` to
``Column(SQLEnum(..., native_enum=False, ...))``. Because
``native_enum=False`` keeps the on-disk type as ``VARCHAR(50)``, the
DDL generated by SQLAlchemy is unchanged — existing rows load
cleanly, no data migration is required, and downgrading the Python
code is purely a code-level rollback.

This migration exists purely to bump the Alembic head so teammates
know the enum-level enforcement landed at this revision. If a future
PR moves to native Postgres enum types, THAT migration will do the
heavy lifting.
"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "e4f5a6b7c8d9"
down_revision: Union[str, None] = "c3d4e5f6g7h8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # No DDL change — see module docstring.
    pass


def downgrade() -> None:
    # No DDL change — see module docstring.
    pass
